=== typelinkmodel/tlm/docs/spec/tlm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified"
        targetNamespace="https://type.link.model.tools/ns/tlm/">


    <!-- common elements and attributes -->

    <xs:element name="id" type="ID"/>
    <xs:element name="name" type="Name"/>
    <xs:element name="description" type="Description"/>
    <xs:attribute name="type" type="TypeName"/>


    <!-- data types -->

    <xs:simpleType name="ID">
        <xs:restriction base="xs:token"/>
    </xs:simpleType>

    <xs:simpleType name="URI">
        <xs:restriction base="xs:anyURI"/>
    </xs:simpleType>

    <xs:simpleType name="Name">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="Description">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="TypeName">
        <xs:union memberTypes="xs:NCName xs:QName"/>
    </xs:simpleType>

    <xs:simpleType name="LinkName">
        <xs:restriction base="xs:NCName"/>
    </xs:simpleType>

    <xs:simpleType name="LinkPath">
        <xs:restriction base="xs:Name"/>
    </xs:simpleType>

    <xs:simpleType name="Value">
        <xs:restriction base="xs:anyType"/>
    </xs:simpleType>

    <xs:simpleType name="Target">
        <xs:restriction base="URI"/>
    </xs:simpleType>


    <!-- data definition -->

    <xs:element name="Data" type="Data"/>

    <xs:complexType name="Data">
        <xs:sequence>
            <xs:any maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <!-- fact definition -->

    <xs:element name="Facts" type="Facts"/>

    <xs:complexType name="Facts">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="Object" type="Object"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Object">
        <xs:sequence>
            <xs:element name="id" type="ID"/>
            <xs:element name="type" type="TypeName"/>
            <xs:element maxOccurs="unbounded" name="Fact" type="Fact"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Fact">
        <xs:sequence>
            <xs:element name="link" type="LinkName"/>
            <xs:choice>
                <!-- link to value type -->
                <xs:sequence>
                    <xs:element name="value" type="Value"/>
                    <xs:element name="type" type="TypeName"/>
                </xs:sequence>
                <!-- link to singular type -->
                <xs:element name="target" type="Target"/>
                <!-- link to plural type -->
                <xs:element maxOccurs="unbounded" name="target" type="LinkName"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>


    <!-- model definition -->

    <xs:element name="Model" type="Model"/>

    <xs:complexType name="Model">
        <xs:annotation>
            <xs:documentation>
                A collection of TLM model statements.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="namespace" type="xs:token">
                <xs:annotation>
                    <xs:documentation>
                        The target namespace this model describes.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" ref="description"/>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="Type" type="Type"/>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="Link" type="Link"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Type">
        <xs:sequence>
            <xs:element name="name" type="TypeName"/>
            <xs:element default="tlm:Type" name="parent" type="TypeName"/>
            <xs:element minOccurs="0" ref="description"/>
            <xs:element minOccurs="0" name="plural" type="TypeName"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Link">
        <xs:annotation>
            <xs:documentation>
                A single TLM model statement.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="from" type="TypeName"/>
            <xs:element name="to" type="TypeName"/>
            <xs:element name="name" type="LinkName"/>
            <xs:element minOccurs="0" ref="description"/>
            <xs:element minOccurs="0" name="primary" type="xs:boolean"/>
            <xs:element minOccurs="0" name="singular" type="xs:boolean"/>
            <xs:element minOccurs="0" name="mandatory" type="xs:boolean"/>
            <xs:element minOccurs="0" name="singularTo" type="xs:boolean"/>
            <xs:element minOccurs="0" name="mandatoryTo" type="xs:boolean"/>
            <xs:element minOccurs="0" name="examples" type="Examples"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Examples">
        <xs:annotation>
            <xs:documentation>
                A collection of partial TLM facts that shows how to use a Link.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="from" type="LinkPath"/>
            <xs:element name="to" type="LinkPath"/>
            <xs:element maxOccurs="unbounded" name="Example" type="Example"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Example">
        <xs:sequence>
            <xs:element name="from" type="Value"/>
            <xs:element name="to" type="Value"/>
            <xs:element name="invalid" default="false" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== typelinkmodel/tlm/docs/design/sample-hr-model.xml
<Model
        xmlns="https://type.link.model.tools/ns/tlm/"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:hr="https://type.link.model.tools/ns/tlm-sample-hr/"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://type.link.model.tools/ns/tlm/ ../spec/tlm.xsd">
    <namespace>hr</namespace>
    <description>The HR namespace is for defining facts about people, departments, and teams.</description>
    <Type>
        <name>Person</name>
        <description>being regarded as an individual</description>
        <plural>People</plural>
    </Type>
    <Type>
        <name>Department</name>
        <description>division of an organization</description>
        <plural>Departments</plural>
    </Type>
    <Type>
        <name>Team</name>
        <description>group of several people associated together</description>
        <plural>Teams</plural>
    </Type>
    <Link>
        <from>Person</from>
        <to>tlm:URI</to>
        <name>id</name>
        <description>A Person is identified by id which must be a URI.</description>
        <primary>true</primary>
    </Link>
    <Link>
        <from>Person</from>
        <to>xs:string</to>
        <name>name</name>
        <description>A Person has exactly one name which must be a string.</description>
        <singular>true</singular>
        <mandatory>true</mandatory>
    </Link>
    <Link>
        <from>Person</from>
        <to>Person</to>
        <name>coachedBy</name>
        <description>A Person can have some coach which must be a Person.</description>
    </Link>
    <Link>
        <from>Person</from>
        <to>xs:boolean</to>
        <name>coaches</name>
        <description>A Person has toggle coaches.</description>
    </Link>
    <Link>
        <from>Department</from>
        <to>tlm:URI</to>
        <name>id</name>
        <description>A Department is identified by id which must be a URI.</description>
        <primary>true</primary>
    </Link>
    <Link>
        <from>Department</from>
        <to>xs:string</to>
        <name>name</name>
        <description>A Department has exactly one name which must be a string.</description>
        <singular>true</singular>
        <mandatory>true</mandatory>
    </Link>
    <Link>
        <from>Department</from>
        <to>Person</to>
        <name>manager</name>
        <description>A Department has exactly one manager which must be a Person.</description>
        <singular>true</singular>
        <mandatory>true</mandatory>
    </Link>
    <Link>
        <from>Person</from>
        <to>Department</to>
        <name>department</name>
        <description>A Person has at most one department which must be a Department.</description>
        <singular>true</singular>
        <mandatory>false</mandatory>
    </Link>
    <Link>
        <from>hr:Team</from>
        <to>tlm:URI</to>
        <name>id</name>
        <description>A Team is identified by id which must be a URI.</description>
        <primary>true</primary>
    </Link>
    <Link>
        <from>hr:Team</from>
        <to>xs:string</to>
        <name>name</name>
        <description>A Team has at most one name which must be a string.</description>
        <singular>true</singular>
        <mandatory>false</mandatory>
    </Link>
    <Link>
        <from>hr:Team</from>
        <to>Person</to>
        <name>lead</name>
        <description>A Team has at least one lead which must be a Person.</description>
        <singular>false</singular>
        <mandatory>true</mandatory>
    </Link>
    <Link>
        <from>Person</from>
        <to>hr:Team</to>
        <name>team</name>
        <description>A Person can have some team which must be a Team.</description>
    </Link>
</Model>
